name: Danger
on: [pull_request]

jobs:
  danger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0
      - name: Install Bundler
        run: gem install bundler
      - name: Install dependencies
        run: bundle install
      - name: Run Danger
        run: bundle exec danger
